defaults:
  - _self_
  - task@_global_: finger_turn_easy

seed: 1

num_epochs: 1000
eval_every_epochs: 10
num_evaluations: 5
batch_size: 16
episode_len: 100
num_workers: 4

same_video: false

use_tb: true

ct_model:
  _target_: ct_model.CTNet
  lr: 10e-4
  lambda_1: 0.
  lambda_2: 0.
  hidden_dim: 1024
  use_tb: ${use_tb}


exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./ct_exp_local/${exp_group}/${exp_id}
