defaults:
  - _self_
  - task@_global_: reacher_hard2

seed: 1

num_epochs: 10000
eval_every_epochs: 60
num_evaluations: 5
batch_size: 32
episode_len: 60
num_workers: 4

use_tb: true

ct_model:
  _target_: ct_model.CTModel
  lr: 1e-4
  hidden_dim: 128

exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./ct_exp_local/${exp_group}/${exp_id}
