defaults:
  - _self_

seed: 1

exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

num_epochs: 10000
eval_every_epochs: 10
num_evaluations: 5
batch_size: 20
episode_len: 100
num_workers: 4

train_finger_video_dir: 'videos/finger/train'
valid_finger_video_dir: 'videos/finger/valid'


use_tb: true

ct_model:
  _target_: ct_model.CTNet
  lr: 10e-4
  lambda_1: 0.2
  lambda_2: 0.2
  hidden_dim: 1024
  use_tb: ${use_tb}



hydra:
  run:
    dir: ./ct_exp_local/${exp_group}/${exp_id}
