defaults:
  - _self_
  - task@_global_: reacher_hard

seed: 1

num_epochs: 5500
eval_every_epochs: 20
num_evaluations: 5
batch_size: 16
episode_len: 25
num_workers: 4

same_video: false

use_tb: true

ct_model:
  _target_: ct_model.CTNet
  lr: 10e-4
  lambda_trans: 1.  # trans loss
  lambda_rec: 1.  # rec loss
  lambda_align: 1.  # align loss
  hidden_dim: 1024
  use_tb: ${use_tb}
  context_size: 4


exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./ct_exp_local/${exp_group}/${exp_id}
