defaults:
  - medium
  - _self_

task_name: button-press-topdown-v2
exp_group: button_press_topdown

cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 100

meta_world: true

context_changer:
  _target_: context_changers.NullContextChanger

metaworld_policy:
  _target_: metaworld.policies.sawyer_button_press_topdown_v2_policy.SawyerButtonPressTopdownV2Policy
