defaults:
  - medium
  - _self_

task_name: door-open-v2
exp_group: door_open

expert_file: exp_local/${exp_group}/1/snapshot.pt
cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 50

meta_world: true

context_changer:
  _target_: context_changers.NullContextChanger
