defaults:
  - medium
  - _self_

task_name: reacher_hard

expert_file: experts/reacher_hard.pt
cmc_file: cmc_exp_local/reacher_hard2/1/snapshot.pt
xml_path: domain_xmls/reacher2.xml

train_cams: [0]
learner_camera_id: 0

train_video_dir: 'videos/reacher_hard2/train'


enc_batch_size: 32
episode_len: 30


exp_group: reacher_hard2

context_changer:
  _target_: context_changers.ReacherHardWCContextChanger
