defaults:
  - medium
  - _self_

task_name: reacher_hard
exp_group: reacher_hard2


xml_path: domain_xmls/reacher.xml

enc_batch_size: 16
episode_len: 60

context_changer:
  _target_: context_changers.ReacherHardWCContextChanger
