defaults:
  - medium
  - _self_

task_name: reacher_hard

expert_file: experts/reacher_hard.pt
cmc_file: cmc_exp_local/reacher_hard2/3/snapshot.pt
xml_path: domain_xmls/reacher2.xml

context_camera_ids: [0]
learner_camera_id: 0

exp_group: reacher_hard2

context_changer:
  _target_: context_changers.ReacherHardContextChanger
