defaults:
  - easy
  - _self_

task_name: walker_run

expert_file: experts/walker_run.pt
ct_file: ct/walker_run.pt
xml_path: domain_xmls/walker.xml

context_camera_ids: [0]
learner_camera_id: 0

context_changer:
  _target_: context_changers.WalkerRunContextChanger
