defaults:
  - medium
  - _self_

task_name: walker_run

expert_file: exp_local/window_close/1/snapshot.pt
ct_file: ct/walker_run.pt
virl_file: virl/walker_run.pt

context_camera_ids: [0]
learner_camera_id: 0

context_changer:
  _target_: context_changers.NullContextChanger
