defaults:
  - _self_
  - task@_global_: reacher_hard

seed: 1

num_epochs: 16001
eval_every_epochs: 60
num_evaluations: 5
batch_size: 64
episode_len: 30
num_workers: 4

same_video: false

use_tb: true
to_lab: true

cmc_model:
  _target_: cmc_model.CMCBasic
  lr: 1e-4
  hidden_dim: 128
  rho: 1



exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./cmc_exp_local/${exp_group}/${exp_id}