defaults:
  - _self_
  - task@_global_: reacher_hard

seed: 1

num_epochs: 16001
eval_every_epochs: 20
num_evaluations: 5
batch_size: 32
episode_len: 30
num_workers: 4

same_video: false

use_tb: true

virl_model:
  _target_: virl_model.ViRLNet
  lr: 10e-4
  lambda_1: 0.7
  lambda_2: 0.1
  lambda_3: 0.1
  lambda_4: 0.1
  hidden_dim: 128
  rho: 1



exp_group: ${now:%Y.%m.%d}
exp_id: ${now:%H%M%S}

hydra:
  run:
    dir: ./virl_exp_local/${exp_group}/${exp_id}
